### ISSUE TITLE
建议增加定制功能

### ISSUE THREAD

**Issue by hwfhc** [starFalll/Ubuntu_Init#1]
可在一个配置文件中选择需要的软件，避免安装不需要的软件

**Comment by starFalll** [comment]
@hwfhc 这个有空的时候我会改一下，你可以提一些自己需要的软件和配置。

**Comment by orrorcol** [comment]
@starFalll 网易云音乐

**Comment by starFalll** [comment]
@liufengshan 我稍后加进去

**Comment by starFalll** [comment]
@liufengshan 已经加进去了，如果有问题请提出。

**Comment by hexueyuan** [comment]
我也觉得如果加一个conf文件用来配置自己想要下载的软件这个功能不错，而且个人感觉事实上一键配置的话，最好不要再执行的过程中出现用户交互行为，因为如果是需要使用这个脚本进行安装的目标用户，往往希望的场景是，我执行了脚本以后，去冲杯咖啡回来安装就完成了，如果中间出现交互的话那用户就必须在执行过程中一直在屏幕前等待，感觉体验不会很好

**Comment by starFalll** [comment]
@hexueyuan 可以提pr

**Comment by starFalll** [comment]
@hwfhc @hexueyuan 刚刚已经将需要安装的软件改成从配置文件config里面读了，不过暂时还没有测试
