### ISSUE TITLE
网易云音乐V1.1不稳定

### ISSUE THREAD

**Issue by orrorcol** [starFalll/Ubuntu_Init#3]
网易云音乐V1.1刚刚发布
可能出现无法启动等各种问题。
[详情见](https://www.deepin.org/2017/11/17/netease-cloud-music-v1-1-for-linux-is-released/)
建议先不安装该版本

**Comment by starFalll** [comment]
@liufengshan 我自己的开发机上面网易云音乐是在upgrade的时候更新的，没有遇到上述问题，我现在去测试机上面看看

**Comment by starFalll** [comment]
@liufengshan 不好意思，测试完忘了回复了，我这边测试V1.1版本没有问题，可以正常使用。旧版本官网我没有找到下载链接，只有v1.1的，所以目前只能安装V1.1。

**Comment by orrorcol** [comment]
好的，如果有人反映问题，[这是老版本的下载地址](http://s1.music.126.net/download/pc/netease-cloud-music_1.0.0_amd64_ubuntu16.04.deb)
